version: '3.8'
services:
  # Postgres database service
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: authdb
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d authdb" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # NestJS application service
  app:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:123123@db:5432/authdb
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
